const STAGE0={
 WORLD_WIDTH:18400,
 WORLD_HEIGHT:1728,
 REFERENCE_HEIGHT:720,
 MAX_GAMEPLAY_ASPECT:Number.POSITIVE_INFINITY,
 CAMERA_DEADZONE_WIDTH:0.52,
 CAMERA_DEADZONE_HEIGHT:0.46
};

const PURSUIT={
 // Simple rule requested for long biomes:
 // when the player's screen is empty, unseen normal enemies run 4x faster.
 EMPTY_SCREEN_SPEED_MULTIPLIER:4,

 // Normal spawn points sit roughly 52 world units outside the camera.
 // Once a rushing enemy reaches this band, its speed immediately returns to normal.
 NORMAL_SPAWN_BAND:65
};

const BALANCE={
 XP_BASE:100,
 XP_PER_LEVEL:15,
 PLAYER_BASE_MAX_HP:100,
 PLAYER_SPEED:220,
 PLAYER_IFRAME_MS:250,
 MANA_REGEN_MS:18000,
 HEART_BASE_CHANCE:0.06,
 HEART_HEAL:25,
 HEART_PITY_HP_THRESHOLD:50,
 HEART_PITY_START_KILLS:4,
 HEART_PITY_STEP:0.025,
 HEART_PITY_MAX_CHANCE:0.22,
 SWORD_DAMAGE_STEP:3,
 SWORD_DAMAGE_CAP:45,
 SWORD_SPEED_FACTOR:0.88,
 SWORD_COOLDOWN_CAP:520,
 SWORD_RADIUS_STEP:18,
 SWORD_RADIUS_CAP:170,
 SHIELD_BLOCK_RESET_MS:1700,
 SHIELD_RELIC_COOLDOWN_MS:25000,
 MAGE_PROJECTILE_SPEED:240,
 MAGE_PROJECTILE_DAMAGE:8,
 MAGE_LEAD_SECONDS:0.32
};


const LOW_HEALTH_CONFIG={
 LOW_THRESHOLD:0.30,
 CRITICAL_THRESHOLD:0.20,
 DEATH_DOOR_THRESHOLD:0.10,
 LOW_PULSE_MS:1200,
 CRITICAL_PULSE_MS:980,
 DEATH_DOOR_PULSE_MS:700,
 CRITICAL_VIGNETTE_ALPHA:0.36,
 DEATH_DOOR_VIGNETTE_ALPHA:0.52,
 VIGNETTE_DEPTH_RATIO:0.28,
 VIGNETTE_DEPTH_MIN:110,
 VIGNETTE_DEPTH_MAX:280,
 VIGNETTE_BANDS:12,
 CRITICAL_FLASH_ALPHA:0.68,
 CRITICAL_FLASH_MS:200,
 RECOVERY_FADE_MS:300,
 HEARTBEAT_LOW_INTERVAL_MS:1080,
 HEARTBEAT_CRITICAL_INTERVAL_MS:820,
 HEARTBEAT_DEATH_DOOR_INTERVAL_MS:620,
 HEARTBEAT_VOLUME:0.48
};

const HERO_SOCKET_DIRS=['n','ne','e','se','s','sw','w','nw'];
const HERO_SOCKET_SPIN_FRAME_COUNT=15;
const HERO_SOCKET_VISUAL_SCALE=0.28;
const HERO_SOCKET_SPIN_FRAME_RATE=20;
const HERO_SOCKET_SPIN_DURATION_MS=Math.ceil(HERO_SOCKET_SPIN_FRAME_COUNT/HERO_SOCKET_SPIN_FRAME_RATE*1000);
const HERO_DEATH_FRAME_COUNT=6;
const HERO_DEATH_ANIMATION_MS=3000;
const HERO_DEATH_HOLD_MS=1000;
// Death frames share a 526x490 transparent canvas. Matching 490 px to the
// live hero's ~224 px source height keeps the on-screen character size stable.
const HERO_DEATH_VISUAL_SCALE=HERO_SOCKET_VISUAL_SCALE*(224/490);

export {
 STAGE0,
 PURSUIT,
 BALANCE,
 LOW_HEALTH_CONFIG,
 HERO_SOCKET_DIRS,
 HERO_SOCKET_SPIN_FRAME_COUNT,
 HERO_SOCKET_VISUAL_SCALE,
 HERO_SOCKET_SPIN_FRAME_RATE,
 HERO_SOCKET_SPIN_DURATION_MS,
 HERO_DEATH_FRAME_COUNT,
 HERO_DEATH_ANIMATION_MS,
 HERO_DEATH_HOLD_MS,
 HERO_DEATH_VISUAL_SCALE
};
