const WORLD_DESIGN={
 ROUTE_Y:864,
 START_X:400,

 // 20:9 mobile view = 1600 world units wide.
 // 7200 / 1600 = 4.5 wide-screen phone views per biome.
 MOBILE_REFERENCE_VIEW_WIDTH:1600,
 ZONE_LENGTH:3600,

 // The final ~1 phone screen of a biome starts showing traces of the next one.
 PREVIEW_WIDTH:800,

 // Once the player is this deep into the new biome, the old route seals.
 BACK_LOCK_DEPTH:600,

 // Old prototype visuals are discarded once safely outside camera range.
 UNLOAD_DEPTH:1200,

 ZONES:[
  {
   id:'ashFields',
   name:'ASH FIELDS',
   subtitle:'The kingdom burned here first',
   start:0,
   end:4000,
   color:0x37372f,
   accent:0x706a58,
   previewKind:'ash',
   landmark:'BROKEN SWORD',
   landmarkX:2275,
   landmarkY:725
  },
  {
   id:'ruinedKingdom',
   name:'RUINED KINGDOM',
   subtitle:'Stone remembers the dead',
   start:4000,
   end:7600,
   color:0x474640,
   accent:0x8b806e,
   previewKind:'ruins',
   landmark:'FALLEN KING',
   landmarkX:5800,
   landmarkY:950
  },
  {
   id:'cursedGraveyard',
   name:'CURSED GRAVEYARD',
   subtitle:'The soil refuses to rest',
   start:7600,
   end:11200,
   color:0x303c35,
   accent:0x668267,
   previewKind:'graveyard',
   landmark:'OLD MAUSOLEUM',
   landmarkX:9400,
   landmarkY:715
  },
  {
   id:'hollowForest',
   name:'HOLLOW FOREST',
   subtitle:'Roots feed on what remains',
   start:11200,
   end:14800,
   color:0x263329,
   accent:0x637c55,
   previewKind:'forest',
   landmark:'DEAD HEART TREE',
   landmarkX:13000,
   landmarkY:960
  },
  {
   id:'spiderTerritory',
   name:'SPIDER TERRITORY',
   subtitle:'Nothing leaves the web',
   start:14800,
   end:18400,
   color:0x29272d,
   accent:0x766d7e,
   previewKind:'spider',
   landmark:'THE GREAT COCOON',
   landmarkX:16600,
   landmarkY:755
  }
 ],

 GATES:[
  {
   id:'saintGate',
   x:4000,
   champion:'brokenSaint',
   fromZone:0,
   toZone:1,
   name:"SAINT'S SEAL",
   closeName:'ASHFALL',
   color:0xd8c878
  },
  {
   id:'soulGate',
   x:7600,
   champion:'necromancer',
   fromZone:1,
   toZone:2,
   name:'SOUL MIST',
   closeName:'SOUL VEIL',
   color:0x67d979
  },
  {
   id:'wardenGate',
   x:11200,
   champion:'shieldWarden',
   fromZone:2,
   toZone:3,
   name:'WARDEN BARRIER',
   closeName:'FALLEN STONE',
   color:0xb8c8d8
  },
  {
   id:'rootGate',
   x:14800,
   champion:'hollowTree',
   fromZone:3,
   toZone:4,
   name:'ROOT WALL',
   closeName:'SEALED ROOTS',
   color:0x91b967
  }
 ]
};

// Regional progression is deliberately layered on top of the existing wave balance.
// Ash Fields is the untouched baseline. Enemy HP/speed formulas still come from the
// current wave system; regions only change ordinary population/spawn pressure and
// grant small permanent hero bonuses after an official biome transition.
const REGION_BALANCE={
 ZONES:[
  {id:'ashFields',populationMultiplier:1.00,spawnRateMultiplier:1.00,playerMaxHpMultiplier:1.00,meleeDamageBonus:0},
  {id:'ruinedKingdom',populationMultiplier:1.15,spawnRateMultiplier:1.05,playerMaxHpMultiplier:1.08,meleeDamageBonus:1},
  {id:'cursedGraveyard',populationMultiplier:1.30,spawnRateMultiplier:1.10,playerMaxHpMultiplier:1.17,meleeDamageBonus:2},
  {id:'hollowForest',populationMultiplier:1.45,spawnRateMultiplier:1.15,playerMaxHpMultiplier:1.26,meleeDamageBonus:3},
  {id:'spiderTerritory',populationMultiplier:1.60,spawnRateMultiplier:1.20,playerMaxHpMultiplier:1.36,meleeDamageBonus:4}
 ]
};



const ASH_FIELDS_CLUSTER_LIBRARY={
 quiet_top_01:[
  {kind:'grass',key:'ash_grass_01',ox:-96,oy:-18,scale:0.34,alpha:0.46,rotation:-0.05},
  {kind:'grass',key:'ash_grass_02',ox:8,oy:-30,scale:0.29,alpha:0.42,rotation:0.04},
  {kind:'rock',key:'ash_rock_03',ox:118,oy:20,scale:0.18,alpha:0.92,rotation:0.05}
 ],
 quiet_bottom_01:[
  {kind:'grass',key:'ash_grass_03',ox:-76,oy:-10,scale:0.28,alpha:0.42,rotation:0.03},
  {kind:'rock',key:'ash_rock_02',ox:48,oy:8,scale:0.21,alpha:0.93,rotation:-0.03},
  {kind:'grass',key:'ash_grass_01',ox:120,oy:-8,scale:0.22,alpha:0.37,rotation:0.02}
 ],
 tree_cluster_top_01:[
  {kind:'tree',key:'ash_tree_01',ox:0,oy:0,scale:0.42,alpha:0.98,rotation:-0.02},
  {kind:'rock',key:'ash_rock_01',ox:-148,oy:112,scale:0.23,alpha:0.96,rotation:-0.06},
  {kind:'rock',key:'ash_rock_03',ox:126,oy:120,scale:0.18,alpha:0.94,rotation:0.05},
  {kind:'grass',key:'ash_grass_02',ox:-104,oy:80,scale:0.24,alpha:0.34,rotation:0.05},
  {kind:'grass',key:'ash_grass_03',ox:116,oy:84,scale:0.21,alpha:0.33,rotation:-0.04}
 ],
 tree_cluster_bottom_01:[
  {kind:'tree',key:'ash_tree_02',ox:0,oy:0,scale:0.39,alpha:0.98,rotation:0.02,flipX:true},
  {kind:'rock',key:'ash_rock_02',ox:-132,oy:112,scale:0.22,alpha:0.95,rotation:-0.05},
  {kind:'rock',key:'ash_rock_03',ox:144,oy:124,scale:0.18,alpha:0.93,rotation:0.06},
  {kind:'grass',key:'ash_grass_01',ox:102,oy:84,scale:0.22,alpha:0.34,rotation:-0.04}
 ],
 rock_cluster_top_01:[
  {kind:'rock',key:'ash_rock_01',ox:-92,oy:6,scale:0.28,alpha:0.96,rotation:-0.05},
  {kind:'rock',key:'ash_rock_02',ox:38,oy:12,scale:0.23,alpha:0.94,rotation:0.03},
  {kind:'rock',key:'ash_rock_03',ox:152,oy:24,scale:0.21,alpha:0.93,rotation:0.06},
  {kind:'grass',key:'ash_grass_02',ox:-8,oy:-20,scale:0.22,alpha:0.32,rotation:0.02},
  {kind:'grass',key:'ash_grass_03',ox:112,oy:-10,scale:0.18,alpha:0.31,rotation:-0.03}
 ],
 rock_cluster_bottom_01:[
  {kind:'rock',key:'ash_rock_02',ox:-86,oy:8,scale:0.24,alpha:0.94,rotation:-0.04},
  {kind:'rock',key:'ash_rock_01',ox:52,oy:-2,scale:0.26,alpha:0.96,rotation:0.04,flipX:true},
  {kind:'grass',key:'ash_grass_03',ox:-6,oy:-20,scale:0.22,alpha:0.31,rotation:0.04},
  {kind:'grass',key:'ash_grass_01',ox:106,oy:-12,scale:0.18,alpha:0.28,rotation:-0.03}
 ],
 tree_solo_top_01:[
  {kind:'tree',key:'ash_tree_02',ox:0,oy:0,scale:0.34,alpha:0.97,rotation:0.03},
  {kind:'rock',key:'ash_rock_03',ox:96,oy:124,scale:0.17,alpha:0.92,rotation:0.05},
  {kind:'grass',key:'ash_grass_02',ox:-92,oy:94,scale:0.18,alpha:0.30,rotation:-0.03}
 ],
 tree_solo_bottom_01:[
  {kind:'tree',key:'ash_tree_01',ox:0,oy:0,scale:0.36,alpha:0.97,rotation:-0.03,flipX:true},
  {kind:'rock',key:'ash_rock_02',ox:-124,oy:118,scale:0.18,alpha:0.92,rotation:-0.04},
  {kind:'grass',key:'ash_grass_01',ox:92,oy:92,scale:0.19,alpha:0.31,rotation:0.03}
 ],
 landmark_sword_support_01:[
  {kind:'tree',key:'ash_tree_02',ox:-282,oy:-12,scale:0.30,alpha:0.95,rotation:-0.02},
  {kind:'rock',key:'ash_rock_01',ox:-184,oy:90,scale:0.27,alpha:0.95,rotation:-0.04},
  {kind:'rock',key:'ash_rock_02',ox:204,oy:82,scale:0.22,alpha:0.93,rotation:0.05},
  {kind:'grass',key:'ash_grass_02',ox:-110,oy:52,scale:0.16,alpha:0.28,rotation:0.05},
  {kind:'grass',key:'ash_grass_03',ox:122,oy:40,scale:0.16,alpha:0.26,rotation:-0.04}
 ],
 landmark_altar_support_01:[
  {kind:'rock',key:'ash_rock_02',ox:-182,oy:88,scale:0.24,alpha:0.93,rotation:-0.04},
  {kind:'rock',key:'ash_rock_03',ox:132,oy:102,scale:0.18,alpha:0.91,rotation:0.05},
  {kind:'tree',key:'ash_tree_01',ox:264,oy:-6,scale:0.28,alpha:0.95,rotation:0.02,flipX:true},
  {kind:'grass',key:'ash_grass_01',ox:164,oy:70,scale:0.18,alpha:0.28,rotation:-0.02}
 ]
};


const ASH_FIELDS_SEGMENTS=[
 {
  id:'intro',
  start:0,
  end:900,
  clusters:[
   {x:470,y:304,cluster:'quiet_top_01'},
   {x:620,y:1390,cluster:'quiet_bottom_01'},
   {x:810,y:352,cluster:'tree_solo_top_01'}
  ],
  landmarks:[]
 },
 {
  id:'burntEdge',
  start:900,
  end:1900,
  clusters:[
   {x:1060,y:1364,cluster:'rock_cluster_bottom_01'},
   {x:1400,y:338,cluster:'tree_cluster_top_01'},
   {x:1690,y:1382,cluster:'tree_cluster_bottom_01'}
  ],
  landmarks:[]
 },
 {
  id:'brokenSword',
  start:1900,
  end:2900,
  clusters:[
   {x:2050,y:326,cluster:'quiet_top_01'},
   {x:2250,y:1058,cluster:'landmark_sword_support_01'},
   {x:2620,y:344,cluster:'rock_cluster_top_01'}
  ],
  landmarks:[
   {key:'ash_landmark_sword',x:2260,y:1260,scale:0.58,rotation:0}
  ]
 },
 {
  id:'postLandmark',
  start:2900,
  end:4000,
  clusters:[
   {x:3010,y:382,cluster:'landmark_altar_support_01'},
   {x:3310,y:1362,cluster:'tree_solo_bottom_01'},
   {x:3560,y:348,cluster:'tree_cluster_top_01'},
   {x:3780,y:1382,cluster:'quiet_bottom_01'}
  ],
  landmarks:[
   {key:'ash_landmark_altar',x:3030,y:470,scale:0.50,rotation:0}
  ]
 }
];


// Baked Ash Fields layout exported from the DEV environment editor on 2026-08-29.
// This is now the clean default world composition, independent of browser localStorage.
// Objects that were originally created in the editor are promoted to ordinary base scenery
// so Reset Segment / Reset All returns to this approved composition instead of deleting them.
const ASH_FIELDS_BAKED_LAYOUT={
 "version": 2,
 "objects": {
  "intro:cluster0:item0": {
   "x": 374,
   "y": 286,
   "scale": 0.34,
   "rotation": -0.05,
   "alpha": 0.46,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_01",
   "kind": "grass",
   "segment": "intro",
   "landmark": false,
   "created": false
  },
  "intro:cluster0:item1": {
   "x": 478,
   "y": 274,
   "scale": 0.29,
   "rotation": 0.04,
   "alpha": 0.42,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_02",
   "kind": "grass",
   "segment": "intro",
   "landmark": false,
   "created": false
  },
  "intro:cluster0:item2": {
   "x": 588,
   "y": 324,
   "scale": 0.18,
   "rotation": 0.05,
   "alpha": 0.92,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_03",
   "kind": "rock",
   "segment": "intro",
   "landmark": false,
   "created": false
  },
  "intro:cluster1:item0": {
   "x": 544,
   "y": 1380,
   "scale": 0.28,
   "rotation": 0.03,
   "alpha": 0.42,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_03",
   "kind": "grass",
   "segment": "intro",
   "landmark": false,
   "created": false
  },
  "intro:cluster1:item1": {
   "x": 668,
   "y": 1398,
   "scale": 0.21,
   "rotation": -0.03,
   "alpha": 0.93,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_02",
   "kind": "rock",
   "segment": "intro",
   "landmark": false,
   "created": false
  },
  "intro:cluster1:item2": {
   "x": 740,
   "y": 1382,
   "scale": 0.22,
   "rotation": 0.02,
   "alpha": 0.37,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_01",
   "kind": "grass",
   "segment": "intro",
   "landmark": false,
   "created": false
  },
  "intro:cluster2:item0": {
   "x": 810,
   "y": 352,
   "scale": 0.34,
   "rotation": 0.03,
   "alpha": 0.97,
   "flipX": false,
   "deleted": false,
   "key": "ash_tree_02",
   "kind": "tree",
   "segment": "intro",
   "landmark": false,
   "created": false
  },
  "intro:cluster2:item1": {
   "x": 906,
   "y": 476,
   "scale": 0.17,
   "rotation": 0.05,
   "alpha": 0.92,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_03",
   "kind": "rock",
   "segment": "intro",
   "landmark": false,
   "created": false
  },
  "intro:cluster2:item2": {
   "x": 718,
   "y": 446,
   "scale": 0.18,
   "rotation": -0.03,
   "alpha": 0.3,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_02",
   "kind": "grass",
   "segment": "intro",
   "landmark": false,
   "created": false
  },
  "burntEdge:cluster0:item0": {
   "x": 974,
   "y": 1372,
   "scale": 0.24,
   "rotation": -0.04,
   "alpha": 0.94,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_02",
   "kind": "rock",
   "segment": "burntEdge",
   "landmark": false,
   "created": false
  },
  "burntEdge:cluster0:item1": {
   "x": 1112,
   "y": 1362,
   "scale": 0.26,
   "rotation": 0.04,
   "alpha": 0.96,
   "flipX": true,
   "deleted": false,
   "key": "ash_rock_01",
   "kind": "rock",
   "segment": "burntEdge",
   "landmark": false,
   "created": false
  },
  "burntEdge:cluster0:item2": {
   "x": 1054,
   "y": 1344,
   "scale": 0.22,
   "rotation": 0.04,
   "alpha": 0.31,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_03",
   "kind": "grass",
   "segment": "burntEdge",
   "landmark": false,
   "created": false
  },
  "burntEdge:cluster0:item3": {
   "x": 1166,
   "y": 1352,
   "scale": 0.18,
   "rotation": -0.03,
   "alpha": 0.28,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_01",
   "kind": "grass",
   "segment": "burntEdge",
   "landmark": false,
   "created": false
  },
  "burntEdge:cluster1:item0": {
   "x": 1400,
   "y": 338,
   "scale": 0.42,
   "rotation": -0.02,
   "alpha": 0.98,
   "flipX": false,
   "deleted": false,
   "key": "ash_tree_01",
   "kind": "tree",
   "segment": "burntEdge",
   "landmark": false,
   "created": false
  },
  "burntEdge:cluster1:item1": {
   "x": 1252,
   "y": 450,
   "scale": 0.23,
   "rotation": -0.06,
   "alpha": 0.96,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_01",
   "kind": "rock",
   "segment": "burntEdge",
   "landmark": false,
   "created": false
  },
  "burntEdge:cluster1:item2": {
   "x": 1526,
   "y": 458,
   "scale": 0.18,
   "rotation": 0.05,
   "alpha": 0.94,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_03",
   "kind": "rock",
   "segment": "burntEdge",
   "landmark": false,
   "created": false
  },
  "burntEdge:cluster1:item3": {
   "x": 1296,
   "y": 418,
   "scale": 0.24,
   "rotation": 0.05,
   "alpha": 0.34,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_02",
   "kind": "grass",
   "segment": "burntEdge",
   "landmark": false,
   "created": false
  },
  "burntEdge:cluster1:item4": {
   "x": 1516,
   "y": 422,
   "scale": 0.21,
   "rotation": -0.04,
   "alpha": 0.33,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_03",
   "kind": "grass",
   "segment": "burntEdge",
   "landmark": false,
   "created": false
  },
  "burntEdge:cluster2:item0": {
   "x": 1690,
   "y": 1382,
   "scale": 0.39,
   "rotation": 0.02,
   "alpha": 0.98,
   "flipX": true,
   "deleted": false,
   "key": "ash_tree_02",
   "kind": "tree",
   "segment": "burntEdge",
   "landmark": false,
   "created": false
  },
  "burntEdge:cluster2:item1": {
   "x": 1558,
   "y": 1494,
   "scale": 0.22,
   "rotation": -0.05,
   "alpha": 0.95,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_02",
   "kind": "rock",
   "segment": "burntEdge",
   "landmark": false,
   "created": false
  },
  "burntEdge:cluster2:item2": {
   "x": 1834,
   "y": 1506,
   "scale": 0.18,
   "rotation": 0.06,
   "alpha": 0.93,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_03",
   "kind": "rock",
   "segment": "burntEdge",
   "landmark": false,
   "created": false
  },
  "burntEdge:cluster2:item3": {
   "x": 1792,
   "y": 1466,
   "scale": 0.22,
   "rotation": -0.04,
   "alpha": 0.34,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_01",
   "kind": "grass",
   "segment": "burntEdge",
   "landmark": false,
   "created": false
  },
  "brokenSword:cluster0:item0": {
   "x": 1954,
   "y": 308,
   "scale": 0.34,
   "rotation": -0.05,
   "alpha": 0.46,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_01",
   "kind": "grass",
   "segment": "brokenSword",
   "landmark": false,
   "created": false
  },
  "brokenSword:cluster0:item1": {
   "x": 2058,
   "y": 296,
   "scale": 0.29,
   "rotation": 0.04,
   "alpha": 0.42,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_02",
   "kind": "grass",
   "segment": "brokenSword",
   "landmark": false,
   "created": false
  },
  "brokenSword:cluster0:item2": {
   "x": 2168,
   "y": 346,
   "scale": 0.18,
   "rotation": 0.05,
   "alpha": 0.92,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_03",
   "kind": "rock",
   "segment": "brokenSword",
   "landmark": false,
   "created": false
  },
  "brokenSword:cluster1:item0": {
   "x": 1879.77,
   "y": 1043.11,
   "scale": 0.3,
   "rotation": -0.02,
   "alpha": 0.95,
   "flipX": false,
   "deleted": false,
   "key": "ash_tree_02",
   "kind": "tree",
   "segment": "brokenSword",
   "landmark": false,
   "created": false
  },
  "brokenSword:cluster1:item1": {
   "x": 2066,
   "y": 1148,
   "scale": 0.27,
   "rotation": -0.04,
   "alpha": 0.95,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_01",
   "kind": "rock",
   "segment": "brokenSword",
   "landmark": false,
   "created": false
  },
  "brokenSword:cluster1:item2": {
   "x": 2454,
   "y": 1140,
   "scale": 0.22,
   "rotation": 0.05,
   "alpha": 0.93,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_02",
   "kind": "rock",
   "segment": "brokenSword",
   "landmark": false,
   "created": false
  },
  "brokenSword:cluster1:item3": {
   "x": 2140,
   "y": 1110,
   "scale": 0.16,
   "rotation": 0.05,
   "alpha": 0.28,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_02",
   "kind": "grass",
   "segment": "brokenSword",
   "landmark": false,
   "created": false
  },
  "brokenSword:cluster1:item4": {
   "x": 2372,
   "y": 1098,
   "scale": 0.16,
   "rotation": -0.04,
   "alpha": 0.26,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_03",
   "kind": "grass",
   "segment": "brokenSword",
   "landmark": false,
   "created": false
  },
  "brokenSword:cluster2:item0": {
   "x": 2528,
   "y": 350,
   "scale": 0.28,
   "rotation": -0.05,
   "alpha": 0.96,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_01",
   "kind": "rock",
   "segment": "brokenSword",
   "landmark": false,
   "created": false
  },
  "brokenSword:cluster2:item1": {
   "x": 2658,
   "y": 356,
   "scale": 0.23,
   "rotation": 0.03,
   "alpha": 0.94,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_02",
   "kind": "rock",
   "segment": "brokenSword",
   "landmark": false,
   "created": false
  },
  "brokenSword:cluster2:item2": {
   "x": 2772,
   "y": 368,
   "scale": 0.21,
   "rotation": 0.06,
   "alpha": 0.93,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_03",
   "kind": "rock",
   "segment": "brokenSword",
   "landmark": false,
   "created": false
  },
  "brokenSword:cluster2:item3": {
   "x": 2612,
   "y": 324,
   "scale": 0.22,
   "rotation": 0.02,
   "alpha": 0.32,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_02",
   "kind": "grass",
   "segment": "brokenSword",
   "landmark": false,
   "created": false
  },
  "brokenSword:cluster2:item4": {
   "x": 2732,
   "y": 334,
   "scale": 0.18,
   "rotation": -0.03,
   "alpha": 0.31,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_03",
   "kind": "grass",
   "segment": "brokenSword",
   "landmark": false,
   "created": false
  },
  "brokenSword:landmark0": {
   "x": 2260,
   "y": 1260,
   "scale": 0.58,
   "rotation": 0,
   "alpha": 0.98,
   "flipX": false,
   "deleted": false,
   "key": "ash_landmark_sword",
   "kind": "landmark",
   "segment": "brokenSword",
   "landmark": true,
   "created": false
  },
  "postLandmark:cluster0:item0": {
   "x": 2828,
   "y": 470,
   "scale": 0.24,
   "rotation": -0.04,
   "alpha": 0.93,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_02",
   "kind": "rock",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "postLandmark:cluster0:item1": {
   "x": 3142,
   "y": 484,
   "scale": 0.18,
   "rotation": 0.05,
   "alpha": 0.91,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_03",
   "kind": "rock",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "postLandmark:cluster0:item2": {
   "x": 3274,
   "y": 376,
   "scale": 0.28,
   "rotation": 0.02,
   "alpha": 0.95,
   "flipX": true,
   "deleted": false,
   "key": "ash_tree_01",
   "kind": "tree",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "postLandmark:cluster0:item3": {
   "x": 3174,
   "y": 452,
   "scale": 0.18,
   "rotation": -0.02,
   "alpha": 0.28,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_01",
   "kind": "grass",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "postLandmark:cluster1:item0": {
   "x": 3310,
   "y": 1362,
   "scale": 0.36,
   "rotation": -0.03,
   "alpha": 0.97,
   "flipX": true,
   "deleted": false,
   "key": "ash_tree_01",
   "kind": "tree",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "postLandmark:cluster1:item1": {
   "x": 3186,
   "y": 1480,
   "scale": 0.18,
   "rotation": -0.04,
   "alpha": 0.92,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_02",
   "kind": "rock",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "postLandmark:cluster1:item2": {
   "x": 3402,
   "y": 1454,
   "scale": 0.19,
   "rotation": 0.03,
   "alpha": 0.31,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_01",
   "kind": "grass",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "postLandmark:cluster2:item0": {
   "x": 3560,
   "y": 348,
   "scale": 0.42,
   "rotation": -0.02,
   "alpha": 0.98,
   "flipX": false,
   "deleted": false,
   "key": "ash_tree_01",
   "kind": "tree",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "postLandmark:cluster2:item1": {
   "x": 3412,
   "y": 460,
   "scale": 0.23,
   "rotation": -0.06,
   "alpha": 0.96,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_01",
   "kind": "rock",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "postLandmark:cluster2:item2": {
   "x": 3686,
   "y": 468,
   "scale": 0.18,
   "rotation": 0.05,
   "alpha": 0.94,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_03",
   "kind": "rock",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "postLandmark:cluster2:item3": {
   "x": 3456,
   "y": 428,
   "scale": 0.24,
   "rotation": 0.05,
   "alpha": 0.34,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_02",
   "kind": "grass",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "postLandmark:cluster2:item4": {
   "x": 3676,
   "y": 432,
   "scale": 0.21,
   "rotation": -0.04,
   "alpha": 0.33,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_03",
   "kind": "grass",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "postLandmark:cluster3:item0": {
   "x": 3704,
   "y": 1372,
   "scale": 0.28,
   "rotation": 0.03,
   "alpha": 0.42,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_03",
   "kind": "grass",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "postLandmark:cluster3:item1": {
   "x": 3828,
   "y": 1390,
   "scale": 0.21,
   "rotation": -0.03,
   "alpha": 0.93,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_02",
   "kind": "rock",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "postLandmark:cluster3:item2": {
   "x": 3900,
   "y": 1374,
   "scale": 0.22,
   "rotation": 0.02,
   "alpha": 0.37,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_01",
   "kind": "grass",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "postLandmark:landmark0": {
   "x": 3030,
   "y": 470,
   "scale": 0.5,
   "rotation": 0,
   "alpha": 0.98,
   "flipX": false,
   "deleted": false,
   "key": "ash_landmark_altar",
   "kind": "landmark",
   "segment": "postLandmark",
   "landmark": true,
   "created": false
  },
  "devCreated:mtdxu8k2:1": {
   "x": 232.36,
   "y": 1103.17,
   "scale": 0.42,
   "rotation": 0,
   "alpha": 0.96,
   "flipX": false,
   "deleted": false,
   "key": "ash_tree_01",
   "kind": "tree",
   "segment": "intro",
   "landmark": false,
   "created": false
  },
  "devCreated:mtdxyhcq:4": {
   "x": 638.5,
   "y": 682.62,
   "scale": 0.24,
   "rotation": 0,
   "alpha": 0.96,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_02",
   "kind": "rock",
   "segment": "intro",
   "landmark": false,
   "created": false
  },
  "devCreated:mtdxz16u:5": {
   "x": 1959.15,
   "y": 74.16,
   "scale": 0.46,
   "rotation": 0,
   "alpha": 0.95,
   "flipX": false,
   "deleted": false,
   "key": "ash_tree_02",
   "kind": "tree",
   "segment": "brokenSword",
   "landmark": false,
   "created": false
  },
  "devCreated:mtdxzj99:6": {
   "x": 1172.04,
   "y": 1376.81,
   "scale": 0.24,
   "rotation": 0,
   "alpha": 1,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_03",
   "kind": "grass",
   "segment": "burntEdge",
   "landmark": false,
   "created": false
  },
  "devCreated:mtdy0bhe:7": {
   "x": 1035.23,
   "y": 1365.02,
   "scale": 0.24,
   "rotation": 0,
   "alpha": 0.9,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_01",
   "kind": "grass",
   "segment": "burntEdge",
   "landmark": false,
   "created": false
  },
  "devCreated:mtdy0npg:8": {
   "x": 1355.04,
   "y": 473.04,
   "scale": 0.24,
   "rotation": 0,
   "alpha": 1,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_02",
   "kind": "grass",
   "segment": "burntEdge",
   "landmark": false,
   "created": false
  },
  "devCreated:mtdy156r:9": {
   "x": 1817.22,
   "y": 471.28,
   "scale": 0.24,
   "rotation": 0,
   "alpha": 0.96,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_01",
   "kind": "rock",
   "segment": "burntEdge",
   "landmark": false,
   "created": false
  },
  "devCreated:mtdy18zx:10": {
   "x": 1903.37,
   "y": 434.71,
   "scale": 0.24,
   "rotation": 0,
   "alpha": 0.96,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_02",
   "kind": "rock",
   "segment": "brokenSword",
   "landmark": false,
   "created": false
  },
  "devCreated:mtdy1j5i:11": {
   "x": 2081.54,
   "y": 565.4,
   "scale": 0.24,
   "rotation": 0,
   "alpha": 0.96,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_03",
   "kind": "rock",
   "segment": "brokenSword",
   "landmark": false,
   "created": false
  },
  "devCreated:mtdy1pv3:12": {
   "x": 1946.73,
   "y": 494.14,
   "scale": 0.24,
   "rotation": 0,
   "alpha": 1,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_03",
   "kind": "grass",
   "segment": "brokenSword",
   "landmark": false,
   "created": false
  },
  "devCreated:mtdy1wmn:13": {
   "x": 1973.71,
   "y": 535.5,
   "scale": 0.24,
   "rotation": 0,
   "alpha": 1,
   "flipX": false,
   "deleted": false,
   "key": "ash_grass_02",
   "kind": "grass",
   "segment": "brokenSword",
   "landmark": false,
   "created": false
  },
  "devCreated:mtejr7vy:1": {
   "x": 1825.15,
   "y": 686.75,
   "scale": 0.36,
   "rotation": 0,
   "alpha": 0.96,
   "flipX": false,
   "deleted": false,
   "key": "ash_tree_01",
   "kind": "tree",
   "segment": "burntEdge",
   "landmark": false,
   "created": false
  },
  "devCreated:mtek8n61:1": {
   "x": 2376.19,
   "y": 533.75,
   "scale": 0.6,
   "rotation": 0,
   "alpha": 0.96,
   "flipX": false,
   "deleted": false,
   "key": "ash_tree_01",
   "kind": "tree",
   "segment": "brokenSword",
   "landmark": false,
   "created": false
  },
  "devCreated:mtek9k5v:2": {
   "x": 3495.21,
   "y": 741.45,
   "scale": 0.24,
   "rotation": 0,
   "alpha": 0.96,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_02",
   "kind": "rock",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "devCreated:mtek9mst:3": {
   "x": 3414.7,
   "y": 802.13,
   "scale": 0.24,
   "rotation": 0,
   "alpha": 0.96,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_02",
   "kind": "rock",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "devCreated:mtek9nu7:4": {
   "x": 3574.56,
   "y": 972.49,
   "scale": 0.24,
   "rotation": 0,
   "alpha": 0.96,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_02",
   "kind": "rock",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "devCreated:mtek9p70:5": {
   "x": 3393.7,
   "y": 1119.51,
   "scale": 0.24,
   "rotation": 0,
   "alpha": 0.96,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_02",
   "kind": "rock",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "devCreated:mtek9spl:6": {
   "x": 3323.68,
   "y": 1009.83,
   "scale": 0.24,
   "rotation": 0,
   "alpha": 0.96,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_03",
   "kind": "rock",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "devCreated:mtek9xal:7": {
   "x": 3456.71,
   "y": 907.14,
   "scale": 0.24,
   "rotation": 0,
   "alpha": 0.96,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_03",
   "kind": "rock",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "devCreated:mteka0jx:8": {
   "x": 3578.06,
   "y": 813.8,
   "scale": 0.24,
   "rotation": 0,
   "alpha": 0.96,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_01",
   "kind": "rock",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "devCreated:mteka28n:9": {
   "x": 3400.7,
   "y": 664.44,
   "scale": 0.24,
   "rotation": 0,
   "alpha": 0.96,
   "flipX": false,
   "deleted": false,
   "key": "ash_rock_01",
   "kind": "rock",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "devCreated:mtekaal3:10": {
   "x": 3593.23,
   "y": 1118.34,
   "scale": 0.36,
   "rotation": 0,
   "alpha": 0.96,
   "flipX": false,
   "deleted": false,
   "key": "ash_tree_02",
   "kind": "tree",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  },
  "devCreated:mtekat92:11": {
   "x": 3314.05,
   "y": 870.64,
   "scale": 0.36,
   "rotation": 0,
   "alpha": 0.96,
   "flipX": false,
   "deleted": false,
   "key": "ash_tree_01",
   "kind": "tree",
   "segment": "postLandmark",
   "landmark": false,
   "created": false
  }
 }
};



const ASH_READABILITY={
 PLAYER_AURA_WIDTH:260,
 PLAYER_AURA_HEIGHT:200,
 PLAYER_SHADOW_WIDTH:48,
 PLAYER_SHADOW_HEIGHT:22,
 PLAYER_SHADOW_Y_OFFSET:12,
 PLAYER_DEATH_SHADOW_Y_OFFSET:2,
 PLAYER_ROUTE_LIGHT_ALPHA:0.045,
 ENEMY_SHADOW_ALPHA:0.26,
 MAGE_SHADOW_ALPHA:0.38,
 MAGE_SHADOW_WIDTH:34,
 MAGE_SHADOW_HEIGHT:10,
 MAGE_SHADOW_Y_OFFSET:2,
 SHIELD_SHADOW_Y_OFFSET:6,
 CHAMPION_SHADOW_ALPHA:0.34
};

export {
 WORLD_DESIGN,
 REGION_BALANCE,
 ASH_FIELDS_CLUSTER_LIBRARY,
 ASH_FIELDS_SEGMENTS,
 ASH_FIELDS_BAKED_LAYOUT,
 ASH_READABILITY
};
